// Mocks generated by Mockito 5.4.4 from annotations
// in marine_nav_app/test/providers/cache_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:marine_nav_app/services/cache_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCacheService extends _i1.Mock implements _i2.CacheService {
  MockCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get maxEntries => (super.noSuchMethod(
        Invocation.getter(#maxEntries),
        returnValue: 0,
      ) as int);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  int get hits => (super.noSuchMethod(
        Invocation.getter(#hits),
        returnValue: 0,
      ) as int);

  @override
  int get misses => (super.noSuchMethod(
        Invocation.getter(#misses),
        returnValue: 0,
      ) as int);

  @override
  int get entryCount => (super.noSuchMethod(
        Invocation.getter(#entryCount),
        returnValue: 0,
      ) as int);

  @override
  int get totalSizeBytes => (super.noSuchMethod(
        Invocation.getter(#totalSizeBytes),
        returnValue: 0,
      ) as int);

  @override
  _i3.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> put(
    String? key,
    String? value, {
    Duration? ttl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            key,
            value,
          ],
          {#ttl: ttl},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> putJson(
    String? key,
    Map<String, dynamic>? json, {
    Duration? ttl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putJson,
          [
            key,
            json,
          ],
          {#ttl: ttl},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  String? get(String? key) => (super.noSuchMethod(Invocation.method(
        #get,
        [key],
      )) as String?);

  @override
  Map<String, dynamic>? getJson(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #getJson,
        [key],
      )) as Map<String, dynamic>?);

  @override
  _i3.Future<void> delete(String? key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
