// Mocks generated by Mockito 5.4.4 from annotations
// in marine_nav_app/test/integration/weather_webgl_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:typed_data' as _i18;
import 'dart:ui' as _i8;

import 'package:latlong2/latlong.dart' as _i15;
import 'package:marine_nav_app/models/lat_lng.dart' as _i12;
import 'package:marine_nav_app/models/nmea_error.dart' as _i17;
import 'package:marine_nav_app/models/route.dart' as _i6;
import 'package:marine_nav_app/models/viewport.dart' as _i4;
import 'package:marine_nav_app/models/weather_data.dart' as _i5;
import 'package:marine_nav_app/providers/cache_provider.dart' as _i3;
import 'package:marine_nav_app/providers/map_provider.dart' as _i9;
import 'package:marine_nav_app/providers/route_provider.dart' as _i14;
import 'package:marine_nav_app/providers/settings_provider.dart' as _i2;
import 'package:marine_nav_app/providers/weather_provider.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;
import 'package:webview_flutter/webview_flutter.dart' as _i11;
import 'package:webview_flutter_platform_interface/webview_flutter_platform_interface.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSettingsProvider_0 extends _i1.SmartFake
    implements _i2.SettingsProvider {
  _FakeSettingsProvider_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCacheProvider_1 extends _i1.SmartFake implements _i3.CacheProvider {
  _FakeCacheProvider_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeViewport_2 extends _i1.SmartFake implements _i4.Viewport {
  _FakeViewport_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWeatherData_3 extends _i1.SmartFake implements _i5.WeatherData {
  _FakeWeatherData_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRoute_4 extends _i1.SmartFake implements _i6.Route {
  _FakeRoute_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlatformWebViewController_5 extends _i1.SmartFake
    implements _i7.PlatformWebViewController {
  _FakePlatformWebViewController_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeObject_6 extends _i1.SmartFake implements Object {
  _FakeObject_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOffset_7 extends _i1.SmartFake implements _i8.Offset {
  _FakeOffset_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MapProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockMapProvider extends _i1.Mock implements _i9.MapProvider {
  MockMapProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SettingsProvider get settingsProvider => (super.noSuchMethod(
        Invocation.getter(#settingsProvider),
        returnValue: _FakeSettingsProvider_0(
          this,
          Invocation.getter(#settingsProvider),
        ),
      ) as _i2.SettingsProvider);

  @override
  _i3.CacheProvider get cacheProvider => (super.noSuchMethod(
        Invocation.getter(#cacheProvider),
        returnValue: _FakeCacheProvider_1(
          this,
          Invocation.getter(#cacheProvider),
        ),
      ) as _i3.CacheProvider);

  @override
  _i4.Viewport get viewport => (super.noSuchMethod(
        Invocation.getter(#viewport),
        returnValue: _FakeViewport_2(
          this,
          Invocation.getter(#viewport),
        ),
      ) as _i4.Viewport);

  @override
  _i10.Stream<_i9.MapError> get errors => (super.noSuchMethod(
        Invocation.getter(#errors),
        returnValue: _i10.Stream<_i9.MapError>.empty(),
      ) as _i10.Stream<_i9.MapError>);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isMapReady => (super.noSuchMethod(
        Invocation.getter(#isMapReady),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i10.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void attachWebView(_i11.WebViewController? controller) => super.noSuchMethod(
        Invocation.method(
          #attachWebView,
          [controller],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> initializeMap(String? apiKey) => (super.noSuchMethod(
        Invocation.method(
          #initializeMap,
          [apiKey],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void handleWebViewEvent(String? message) => super.noSuchMethod(
        Invocation.method(
          #handleWebViewEvent,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void syncToWebView() => super.noSuchMethod(
        Invocation.method(
          #syncToWebView,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateViewport(_i4.Viewport? next) => super.noSuchMethod(
        Invocation.method(
          #updateViewport,
          [next],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setCenter(_i12.LatLng? center) => super.noSuchMethod(
        Invocation.method(
          #setCenter,
          [center],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setZoom(double? zoom) => super.noSuchMethod(
        Invocation.method(
          #setZoom,
          [zoom],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setRotation(double? rotation) => super.noSuchMethod(
        Invocation.method(
          #setRotation,
          [rotation],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSize(_i8.Size? size) => super.noSuchMethod(
        Invocation.method(
          #setSize,
          [size],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> flyTo(
    _i12.LatLng? target, {
    double? zoom,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #flyTo,
          [target],
          {#zoom: zoom},
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updateBoatMarker(
    double? lat,
    double? lng,
    double? headingDeg,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBoatMarker,
          [
            lat,
            lng,
            headingDeg,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updateTrackLine(List<List<num>>? coords) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTrackLine,
          [coords],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> clearTrackLine() => (super.noSuchMethod(
        Invocation.method(
          #clearTrackLine,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void reportError(_i9.MapError? error) => super.noSuchMethod(
        Invocation.method(
          #reportError,
          [error],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [WeatherProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherProvider extends _i1.Mock implements _i13.WeatherProvider {
  MockWeatherProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.WeatherData get data => (super.noSuchMethod(
        Invocation.getter(#data),
        returnValue: _FakeWeatherData_3(
          this,
          Invocation.getter(#data),
        ),
      ) as _i5.WeatherData);

  @override
  bool get hasData => (super.noSuchMethod(
        Invocation.getter(#hasData),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get isWindVisible => (super.noSuchMethod(
        Invocation.getter(#isWindVisible),
        returnValue: false,
      ) as bool);

  @override
  bool get isWaveVisible => (super.noSuchMethod(
        Invocation.getter(#isWaveVisible),
        returnValue: false,
      ) as bool);

  @override
  bool get isStale => (super.noSuchMethod(
        Invocation.getter(#isStale),
        returnValue: false,
      ) as bool);

  @override
  _i2.SettingsProvider get settings => (super.noSuchMethod(
        Invocation.getter(#settings),
        returnValue: _FakeSettingsProvider_0(
          this,
          Invocation.getter(#settings),
        ),
      ) as _i2.SettingsProvider);

  @override
  _i3.CacheProvider get cache => (super.noSuchMethod(
        Invocation.getter(#cache),
        returnValue: _FakeCacheProvider_1(
          this,
          Invocation.getter(#cache),
        ),
      ) as _i3.CacheProvider);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  bool isLayerActive(_i13.WeatherLayer? layer) => (super.noSuchMethod(
        Invocation.method(
          #isLayerActive,
          [layer],
        ),
        returnValue: false,
      ) as bool);

  @override
  void toggleLayer(_i13.WeatherLayer? layer) => super.noSuchMethod(
        Invocation.method(
          #toggleLayer,
          [layer],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLayerActive(
    _i13.WeatherLayer? layer, {
    required bool? active,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #setLayerActive,
          [layer],
          {#active: active},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void fetchForViewport({
    required double? south,
    required double? north,
    required double? west,
    required double? east,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #fetchForViewport,
          [],
          {
            #south: south,
            #north: north,
            #west: west,
            #east: east,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> refresh({
    required double? south,
    required double? north,
    required double? west,
    required double? east,
    bool? force = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
          {
            #south: south,
            #north: north,
            #west: west,
            #east: east,
            #force: force,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void clearData() => super.noSuchMethod(
        Invocation.method(
          #clearData,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RouteProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockRouteProvider extends _i1.Mock implements _i14.RouteProvider {
  MockRouteProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i6.Route> get savedRoutes => (super.noSuchMethod(
        Invocation.getter(#savedRoutes),
        returnValue: <_i6.Route>[],
      ) as List<_i6.Route>);

  @override
  int get currentWaypointIndex => (super.noSuchMethod(
        Invocation.getter(#currentWaypointIndex),
        returnValue: 0,
      ) as int);

  @override
  double get distanceToNextWaypoint => (super.noSuchMethod(
        Invocation.getter(#distanceToNextWaypoint),
        returnValue: 0.0,
      ) as double);

  @override
  double get bearingToNextWaypoint => (super.noSuchMethod(
        Invocation.getter(#bearingToNextWaypoint),
        returnValue: 0.0,
      ) as double);

  @override
  double get totalRouteDistance => (super.noSuchMethod(
        Invocation.getter(#totalRouteDistance),
        returnValue: 0.0,
      ) as double);

  @override
  double get distanceRemaining => (super.noSuchMethod(
        Invocation.getter(#distanceRemaining),
        returnValue: 0.0,
      ) as double);

  @override
  double get routeProgress => (super.noSuchMethod(
        Invocation.getter(#routeProgress),
        returnValue: 0.0,
      ) as double);

  @override
  double get crossTrackError => (super.noSuchMethod(
        Invocation.getter(#crossTrackError),
        returnValue: 0.0,
      ) as double);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  double getETAToNextWaypoint(double? speedKnots) => (super.noSuchMethod(
        Invocation.method(
          #getETAToNextWaypoint,
          [speedKnots],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  void activateRoute(_i6.Route? route) => super.noSuchMethod(
        Invocation.method(
          #activateRoute,
          [route],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updatePosition(_i15.LatLng? position) => super.noSuchMethod(
        Invocation.method(
          #updatePosition,
          [position],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void advanceWaypoint() => super.noSuchMethod(
        Invocation.method(
          #advanceWaypoint,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void revertWaypoint() => super.noSuchMethod(
        Invocation.method(
          #revertWaypoint,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deactivateRoute() => super.noSuchMethod(
        Invocation.method(
          #deactivateRoute,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearPosition() => super.noSuchMethod(
        Invocation.method(
          #clearPosition,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> saveRoute(_i6.Route? route) => (super.noSuchMethod(
        Invocation.method(
          #saveRoute,
          [route],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteRoute(String? routeId) => (super.noSuchMethod(
        Invocation.method(
          #deleteRoute,
          [routeId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i6.Route> createRoute({
    required String? name,
    required List<_i6.Waypoint>? waypoints,
    String? description,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRoute,
          [],
          {
            #name: name,
            #waypoints: waypoints,
            #description: description,
          },
        ),
        returnValue: _i10.Future<_i6.Route>.value(_FakeRoute_4(
          this,
          Invocation.method(
            #createRoute,
            [],
            {
              #name: name,
              #waypoints: waypoints,
              #description: description,
            },
          ),
        )),
      ) as _i10.Future<_i6.Route>);

  @override
  _i10.Future<void> loadSavedRoutes() => (super.noSuchMethod(
        Invocation.method(
          #loadSavedRoutes,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SettingsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsProvider extends _i1.Mock implements _i2.SettingsProvider {
  MockSettingsProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SpeedUnit get speedUnit => (super.noSuchMethod(
        Invocation.getter(#speedUnit),
        returnValue: _i2.SpeedUnit.knots,
      ) as _i2.SpeedUnit);

  @override
  _i2.DistanceUnit get distanceUnit => (super.noSuchMethod(
        Invocation.getter(#distanceUnit),
        returnValue: _i2.DistanceUnit.nauticalMiles,
      ) as _i2.DistanceUnit);

  @override
  _i2.DepthUnit get depthUnit => (super.noSuchMethod(
        Invocation.getter(#depthUnit),
        returnValue: _i2.DepthUnit.meters,
      ) as _i2.DepthUnit);

  @override
  bool get showCompass => (super.noSuchMethod(
        Invocation.getter(#showCompass),
        returnValue: false,
      ) as bool);

  @override
  bool get showDataOrbs => (super.noSuchMethod(
        Invocation.getter(#showDataOrbs),
        returnValue: false,
      ) as bool);

  @override
  bool get showSpeedArc => (super.noSuchMethod(
        Invocation.getter(#showSpeedArc),
        returnValue: false,
      ) as bool);

  @override
  bool get showWaveAnimation => (super.noSuchMethod(
        Invocation.getter(#showWaveAnimation),
        returnValue: false,
      ) as bool);

  @override
  String get language => (super.noSuchMethod(
        Invocation.getter(#language),
        returnValue: _i16.dummyValue<String>(
          this,
          Invocation.getter(#language),
        ),
      ) as String);

  @override
  int get mapRefreshRate => (super.noSuchMethod(
        Invocation.getter(#mapRefreshRate),
        returnValue: 0,
      ) as int);

  @override
  String get nmeaHost => (super.noSuchMethod(
        Invocation.getter(#nmeaHost),
        returnValue: _i16.dummyValue<String>(
          this,
          Invocation.getter(#nmeaHost),
        ),
      ) as String);

  @override
  int get nmeaPort => (super.noSuchMethod(
        Invocation.getter(#nmeaPort),
        returnValue: 0,
      ) as int);

  @override
  _i17.ConnectionType get nmeaConnectionType => (super.noSuchMethod(
        Invocation.getter(#nmeaConnectionType),
        returnValue: _i17.ConnectionType.tcp,
      ) as _i17.ConnectionType);

  @override
  bool get autoConnectNMEA => (super.noSuchMethod(
        Invocation.getter(#autoConnectNMEA),
        returnValue: false,
      ) as bool);

  @override
  String get mapTilerApiKey => (super.noSuchMethod(
        Invocation.getter(#mapTilerApiKey),
        returnValue: _i16.dummyValue<String>(
          this,
          Invocation.getter(#mapTilerApiKey),
        ),
      ) as String);

  @override
  bool get hasMapTilerApiKey => (super.noSuchMethod(
        Invocation.getter(#hasMapTilerApiKey),
        returnValue: false,
      ) as bool);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i10.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setSpeedUnit(_i2.SpeedUnit? unit) => (super.noSuchMethod(
        Invocation.method(
          #setSpeedUnit,
          [unit],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setDistanceUnit(_i2.DistanceUnit? unit) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDistanceUnit,
          [unit],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setDepthUnit(_i2.DepthUnit? unit) => (super.noSuchMethod(
        Invocation.method(
          #setDepthUnit,
          [unit],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setShowCompass(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setShowCompass,
          [value],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setShowDataOrbs(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setShowDataOrbs,
          [value],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setShowSpeedArc(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setShowSpeedArc,
          [value],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setShowWaveAnimation(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setShowWaveAnimation,
          [value],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setLanguage(String? lang) => (super.noSuchMethod(
        Invocation.method(
          #setLanguage,
          [lang],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setMapRefreshRate(int? milliseconds) => (super.noSuchMethod(
        Invocation.method(
          #setMapRefreshRate,
          [milliseconds],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setNMEAHost(String? host) => (super.noSuchMethod(
        Invocation.method(
          #setNMEAHost,
          [host],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setNMEAPort(int? port) => (super.noSuchMethod(
        Invocation.method(
          #setNMEAPort,
          [port],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setNMEAConnectionType(_i17.ConnectionType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNMEAConnectionType,
          [type],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setAutoConnectNMEA(bool? autoConnect) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAutoConnectNMEA,
          [autoConnect],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setMapTilerApiKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #setMapTilerApiKey,
          [key],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> resetToDefaults() => (super.noSuchMethod(
        Invocation.method(
          #resetToDefaults,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [WebViewController].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebViewController extends _i1.Mock implements _i11.WebViewController {
  MockWebViewController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.PlatformWebViewController get platform => (super.noSuchMethod(
        Invocation.getter(#platform),
        returnValue: _FakePlatformWebViewController_5(
          this,
          Invocation.getter(#platform),
        ),
      ) as _i7.PlatformWebViewController);

  @override
  _i10.Future<void> loadFile(String? absoluteFilePath) => (super.noSuchMethod(
        Invocation.method(
          #loadFile,
          [absoluteFilePath],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> loadFlutterAsset(String? key) => (super.noSuchMethod(
        Invocation.method(
          #loadFlutterAsset,
          [key],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> loadHtmlString(
    String? html, {
    String? baseUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadHtmlString,
          [html],
          {#baseUrl: baseUrl},
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> loadRequest(
    Uri? uri, {
    _i11.LoadRequestMethod? method = _i11.LoadRequestMethod.get,
    Map<String, String>? headers = const {},
    _i18.Uint8List? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadRequest,
          [uri],
          {
            #method: method,
            #headers: headers,
            #body: body,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<String?> currentUrl() => (super.noSuchMethod(
        Invocation.method(
          #currentUrl,
          [],
        ),
        returnValue: _i10.Future<String?>.value(),
      ) as _i10.Future<String?>);

  @override
  _i10.Future<bool> canGoBack() => (super.noSuchMethod(
        Invocation.method(
          #canGoBack,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<bool> canGoForward() => (super.noSuchMethod(
        Invocation.method(
          #canGoForward,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<void> goBack() => (super.noSuchMethod(
        Invocation.method(
          #goBack,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> goForward() => (super.noSuchMethod(
        Invocation.method(
          #goForward,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setNavigationDelegate(_i11.NavigationDelegate? delegate) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNavigationDelegate,
          [delegate],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> clearLocalStorage() => (super.noSuchMethod(
        Invocation.method(
          #clearLocalStorage,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> runJavaScript(String? javaScript) => (super.noSuchMethod(
        Invocation.method(
          #runJavaScript,
          [javaScript],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<Object> runJavaScriptReturningResult(String? javaScript) =>
      (super.noSuchMethod(
        Invocation.method(
          #runJavaScriptReturningResult,
          [javaScript],
        ),
        returnValue: _i10.Future<Object>.value(_FakeObject_6(
          this,
          Invocation.method(
            #runJavaScriptReturningResult,
            [javaScript],
          ),
        )),
      ) as _i10.Future<Object>);

  @override
  _i10.Future<void> addJavaScriptChannel(
    String? name, {
    required void Function(_i11.JavaScriptMessage)? onMessageReceived,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addJavaScriptChannel,
          [name],
          {#onMessageReceived: onMessageReceived},
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> removeJavaScriptChannel(String? javaScriptChannelName) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeJavaScriptChannel,
          [javaScriptChannelName],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<String?> getTitle() => (super.noSuchMethod(
        Invocation.method(
          #getTitle,
          [],
        ),
        returnValue: _i10.Future<String?>.value(),
      ) as _i10.Future<String?>);

  @override
  _i10.Future<void> scrollTo(
    int? x,
    int? y,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #scrollTo,
          [
            x,
            y,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> scrollBy(
    int? x,
    int? y,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #scrollBy,
          [
            x,
            y,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i8.Offset> getScrollPosition() => (super.noSuchMethod(
        Invocation.method(
          #getScrollPosition,
          [],
        ),
        returnValue: _i10.Future<_i8.Offset>.value(_FakeOffset_7(
          this,
          Invocation.method(
            #getScrollPosition,
            [],
          ),
        )),
      ) as _i10.Future<_i8.Offset>);

  @override
  _i10.Future<void> enableZoom(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #enableZoom,
          [enabled],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setBackgroundColor(_i8.Color? color) => (super.noSuchMethod(
        Invocation.method(
          #setBackgroundColor,
          [color],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setJavaScriptMode(_i11.JavaScriptMode? javaScriptMode) =>
      (super.noSuchMethod(
        Invocation.method(
          #setJavaScriptMode,
          [javaScriptMode],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setUserAgent(String? userAgent) => (super.noSuchMethod(
        Invocation.method(
          #setUserAgent,
          [userAgent],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setOnConsoleMessage(
          void Function(_i11.JavaScriptConsoleMessage)? onConsoleMessage) =>
      (super.noSuchMethod(
        Invocation.method(
          #setOnConsoleMessage,
          [onConsoleMessage],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setOnJavaScriptAlertDialog(
          _i10.Future<void> Function(_i11.JavaScriptAlertDialogRequest)?
              onJavaScriptAlertDialog) =>
      (super.noSuchMethod(
        Invocation.method(
          #setOnJavaScriptAlertDialog,
          [onJavaScriptAlertDialog],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setOnJavaScriptConfirmDialog(
          _i10.Future<bool> Function(_i11.JavaScriptConfirmDialogRequest)?
              onJavaScriptConfirmDialog) =>
      (super.noSuchMethod(
        Invocation.method(
          #setOnJavaScriptConfirmDialog,
          [onJavaScriptConfirmDialog],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setOnJavaScriptTextInputDialog(
          _i10.Future<String> Function(_i11.JavaScriptTextInputDialogRequest)?
              onJavaScriptTextInputDialog) =>
      (super.noSuchMethod(
        Invocation.method(
          #setOnJavaScriptTextInputDialog,
          [onJavaScriptTextInputDialog],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<String?> getUserAgent() => (super.noSuchMethod(
        Invocation.method(
          #getUserAgent,
          [],
        ),
        returnValue: _i10.Future<String?>.value(),
      ) as _i10.Future<String?>);

  @override
  _i10.Future<void> setOnScrollPositionChange(
          void Function(_i11.ScrollPositionChange)? onScrollPositionChange) =>
      (super.noSuchMethod(
        Invocation.method(
          #setOnScrollPositionChange,
          [onScrollPositionChange],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setVerticalScrollBarEnabled(bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setVerticalScrollBarEnabled,
          [enabled],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setHorizontalScrollBarEnabled(bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setHorizontalScrollBarEnabled,
          [enabled],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<bool> supportsSetScrollBarsEnabled() => (super.noSuchMethod(
        Invocation.method(
          #supportsSetScrollBarsEnabled,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<void> setOverScrollMode(_i11.WebViewOverScrollMode? mode) =>
      (super.noSuchMethod(
        Invocation.method(
          #setOverScrollMode,
          [mode],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}
