// Mocks generated by Mockito 5.4.4 from annotations
// in marine_nav_app/test/integration/weather_stack_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;
import 'dart:ui' as _i15;

import 'package:flutter/foundation.dart' as _i9;
import 'package:flutter/material.dart' as _i8;
import 'package:latlong2/latlong.dart' as _i21;
import 'package:marine_nav_app/models/ais_target.dart' as _i11;
import 'package:marine_nav_app/models/boat_position.dart' as _i17;
import 'package:marine_nav_app/models/lat_lng.dart' as _i14;
import 'package:marine_nav_app/models/nmea_error.dart' as _i24;
import 'package:marine_nav_app/models/route.dart' as _i7;
import 'package:marine_nav_app/models/viewport.dart' as _i5;
import 'package:marine_nav_app/models/weather_data.dart' as _i6;
import 'package:marine_nav_app/providers/ais_provider.dart' as _i10;
import 'package:marine_nav_app/providers/boat_provider.dart' as _i16;
import 'package:marine_nav_app/providers/cache_provider.dart' as _i4;
import 'package:marine_nav_app/providers/map_provider.dart' as _i18;
import 'package:marine_nav_app/providers/route_provider.dart' as _i20;
import 'package:marine_nav_app/providers/settings_provider.dart' as _i3;
import 'package:marine_nav_app/providers/theme_provider.dart' as _i25;
import 'package:marine_nav_app/providers/timeline_provider.dart' as _i22;
import 'package:marine_nav_app/providers/weather_provider.dart' as _i19;
import 'package:marine_nav_app/services/ais_service.dart' as _i12;
import 'package:marine_nav_app/services/anchor_alarm_service.dart' as _i2;
import 'package:marine_nav_app/theme/theme_variant.dart' as _i26;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i23;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAnchorAlarmService_0 extends _i1.SmartFake
    implements _i2.AnchorAlarmService {
  _FakeAnchorAlarmService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSettingsProvider_1 extends _i1.SmartFake
    implements _i3.SettingsProvider {
  _FakeSettingsProvider_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCacheProvider_2 extends _i1.SmartFake implements _i4.CacheProvider {
  _FakeCacheProvider_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeViewport_3 extends _i1.SmartFake implements _i5.Viewport {
  _FakeViewport_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWeatherData_4 extends _i1.SmartFake implements _i6.WeatherData {
  _FakeWeatherData_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRoute_5 extends _i1.SmartFake implements _i7.Route {
  _FakeRoute_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeThemeData_6 extends _i1.SmartFake implements _i8.ThemeData {
  _FakeThemeData_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i9.DiagnosticLevel? minLevel = _i9.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [AisProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAisProvider extends _i1.Mock implements _i10.AisProvider {
  MockAisProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<int, _i11.AisTarget> get targets => (super.noSuchMethod(
        Invocation.getter(#targets),
        returnValue: <int, _i11.AisTarget>{},
      ) as Map<int, _i11.AisTarget>);

  @override
  List<_i11.AisTarget> get warnings => (super.noSuchMethod(
        Invocation.getter(#warnings),
        returnValue: <_i11.AisTarget>[],
      ) as List<_i11.AisTarget>);

  @override
  _i12.AisConnectionState get connectionState => (super.noSuchMethod(
        Invocation.getter(#connectionState),
        returnValue: _i12.AisConnectionState.disconnected,
      ) as _i12.AisConnectionState);

  @override
  int get targetCount => (super.noSuchMethod(
        Invocation.getter(#targetCount),
        returnValue: 0,
      ) as int);

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i13.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> connect({
    required double? swLat,
    required double? swLng,
    required double? neLat,
    required double? neLng,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
          {
            #swLat: swLat,
            #swLng: swLng,
            #neLat: neLat,
            #neLng: neLng,
          },
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> updateViewport({
    required double? swLat,
    required double? swLng,
    required double? neLat,
    required double? neLng,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateViewport,
          [],
          {
            #swLat: swLat,
            #swLng: swLng,
            #neLat: neLat,
            #neLng: neLng,
          },
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void updateOwnVessel({
    required _i14.LatLng? position,
    required double? sogKnots,
    required double? cogDegrees,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #updateOwnVessel,
          [],
          {
            #position: position,
            #sogKnots: sogKnots,
            #cogDegrees: cogDegrees,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [BoatProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockBoatProvider extends _i1.Mock implements _i16.BoatProvider {
  MockBoatProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.PositionSource get source => (super.noSuchMethod(
        Invocation.getter(#source),
        returnValue: _i16.PositionSource.none,
      ) as _i16.PositionSource);

  @override
  List<_i17.TrackPoint> get trackHistory => (super.noSuchMethod(
        Invocation.getter(#trackHistory),
        returnValue: <_i17.TrackPoint>[],
      ) as List<_i17.TrackPoint>);

  @override
  int get trackPointCount => (super.noSuchMethod(
        Invocation.getter(#trackPointCount),
        returnValue: 0,
      ) as int);

  @override
  bool get followBoat => (super.noSuchMethod(
        Invocation.getter(#followBoat),
        returnValue: false,
      ) as bool);

  @override
  bool get showTrack => (super.noSuchMethod(
        Invocation.getter(#showTrack),
        returnValue: false,
      ) as bool);

  @override
  _i2.AnchorAlarmService get anchorAlarm => (super.noSuchMethod(
        Invocation.getter(#anchorAlarm),
        returnValue: _FakeAnchorAlarmService_0(
          this,
          Invocation.getter(#anchorAlarm),
        ),
      ) as _i2.AnchorAlarmService);

  @override
  set followBoat(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #followBoat,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set showTrack(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #showTrack,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void clearTrack() => super.noSuchMethod(
        Invocation.method(
          #clearTrack,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MapProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockMapProvider extends _i1.Mock implements _i18.MapProvider {
  MockMapProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SettingsProvider get settingsProvider => (super.noSuchMethod(
        Invocation.getter(#settingsProvider),
        returnValue: _FakeSettingsProvider_1(
          this,
          Invocation.getter(#settingsProvider),
        ),
      ) as _i3.SettingsProvider);

  @override
  _i4.CacheProvider get cacheProvider => (super.noSuchMethod(
        Invocation.getter(#cacheProvider),
        returnValue: _FakeCacheProvider_2(
          this,
          Invocation.getter(#cacheProvider),
        ),
      ) as _i4.CacheProvider);

  @override
  _i5.Viewport get viewport => (super.noSuchMethod(
        Invocation.getter(#viewport),
        returnValue: _FakeViewport_3(
          this,
          Invocation.getter(#viewport),
        ),
      ) as _i5.Viewport);

  @override
  _i13.Stream<_i18.MapError> get errors => (super.noSuchMethod(
        Invocation.getter(#errors),
        returnValue: _i13.Stream<_i18.MapError>.empty(),
      ) as _i13.Stream<_i18.MapError>);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isMapReady => (super.noSuchMethod(
        Invocation.getter(#isMapReady),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i13.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void handleMapReady(dynamic controller) => super.noSuchMethod(
        Invocation.method(
          #handleMapReady,
          [controller],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateBoatMarker(
    double? lat,
    double? lng,
    double? heading,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateBoatMarker,
          [
            lat,
            lng,
            heading,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateTrackLine(List<List<double>>? points) => super.noSuchMethod(
        Invocation.method(
          #updateTrackLine,
          [points],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearTrackLine() => super.noSuchMethod(
        Invocation.method(
          #clearTrackLine,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateViewport(_i5.Viewport? next) => super.noSuchMethod(
        Invocation.method(
          #updateViewport,
          [next],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setCenter(_i14.LatLng? center) => super.noSuchMethod(
        Invocation.method(
          #setCenter,
          [center],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setZoom(double? zoom) => super.noSuchMethod(
        Invocation.method(
          #setZoom,
          [zoom],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setRotation(double? rotation) => super.noSuchMethod(
        Invocation.method(
          #setRotation,
          [rotation],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSize(_i15.Size? size) => super.noSuchMethod(
        Invocation.method(
          #setSize,
          [size],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<void> flyTo(
    _i14.LatLng? target, {
    double? zoom,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #flyTo,
          [target],
          {#zoom: zoom},
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void reportError(_i18.MapError? error) => super.noSuchMethod(
        Invocation.method(
          #reportError,
          [error],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [WeatherProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherProvider extends _i1.Mock implements _i19.WeatherProvider {
  MockWeatherProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.WeatherData get data => (super.noSuchMethod(
        Invocation.getter(#data),
        returnValue: _FakeWeatherData_4(
          this,
          Invocation.getter(#data),
        ),
      ) as _i6.WeatherData);

  @override
  bool get hasData => (super.noSuchMethod(
        Invocation.getter(#hasData),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get isWindVisible => (super.noSuchMethod(
        Invocation.getter(#isWindVisible),
        returnValue: false,
      ) as bool);

  @override
  bool get isWaveVisible => (super.noSuchMethod(
        Invocation.getter(#isWaveVisible),
        returnValue: false,
      ) as bool);

  @override
  bool get isStale => (super.noSuchMethod(
        Invocation.getter(#isStale),
        returnValue: false,
      ) as bool);

  @override
  _i3.SettingsProvider get settings => (super.noSuchMethod(
        Invocation.getter(#settings),
        returnValue: _FakeSettingsProvider_1(
          this,
          Invocation.getter(#settings),
        ),
      ) as _i3.SettingsProvider);

  @override
  _i4.CacheProvider get cache => (super.noSuchMethod(
        Invocation.getter(#cache),
        returnValue: _FakeCacheProvider_2(
          this,
          Invocation.getter(#cache),
        ),
      ) as _i4.CacheProvider);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  bool isLayerActive(_i19.WeatherLayer? layer) => (super.noSuchMethod(
        Invocation.method(
          #isLayerActive,
          [layer],
        ),
        returnValue: false,
      ) as bool);

  @override
  void toggleLayer(_i19.WeatherLayer? layer) => super.noSuchMethod(
        Invocation.method(
          #toggleLayer,
          [layer],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLayerActive(
    _i19.WeatherLayer? layer, {
    required bool? active,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #setLayerActive,
          [layer],
          {#active: active},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void fetchForViewport({
    required double? south,
    required double? north,
    required double? west,
    required double? east,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #fetchForViewport,
          [],
          {
            #south: south,
            #north: north,
            #west: west,
            #east: east,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<void> refresh({
    required double? south,
    required double? north,
    required double? west,
    required double? east,
    bool? force = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
          {
            #south: south,
            #north: north,
            #west: west,
            #east: east,
            #force: force,
          },
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void clearData() => super.noSuchMethod(
        Invocation.method(
          #clearData,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RouteProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockRouteProvider extends _i1.Mock implements _i20.RouteProvider {
  MockRouteProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i7.Route> get savedRoutes => (super.noSuchMethod(
        Invocation.getter(#savedRoutes),
        returnValue: <_i7.Route>[],
      ) as List<_i7.Route>);

  @override
  int get currentWaypointIndex => (super.noSuchMethod(
        Invocation.getter(#currentWaypointIndex),
        returnValue: 0,
      ) as int);

  @override
  double get distanceToNextWaypoint => (super.noSuchMethod(
        Invocation.getter(#distanceToNextWaypoint),
        returnValue: 0.0,
      ) as double);

  @override
  double get bearingToNextWaypoint => (super.noSuchMethod(
        Invocation.getter(#bearingToNextWaypoint),
        returnValue: 0.0,
      ) as double);

  @override
  double get totalRouteDistance => (super.noSuchMethod(
        Invocation.getter(#totalRouteDistance),
        returnValue: 0.0,
      ) as double);

  @override
  double get distanceRemaining => (super.noSuchMethod(
        Invocation.getter(#distanceRemaining),
        returnValue: 0.0,
      ) as double);

  @override
  double get routeProgress => (super.noSuchMethod(
        Invocation.getter(#routeProgress),
        returnValue: 0.0,
      ) as double);

  @override
  double get crossTrackError => (super.noSuchMethod(
        Invocation.getter(#crossTrackError),
        returnValue: 0.0,
      ) as double);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  double getETAToNextWaypoint(double? speedKnots) => (super.noSuchMethod(
        Invocation.method(
          #getETAToNextWaypoint,
          [speedKnots],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  void activateRoute(_i7.Route? route) => super.noSuchMethod(
        Invocation.method(
          #activateRoute,
          [route],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updatePosition(_i21.LatLng? position) => super.noSuchMethod(
        Invocation.method(
          #updatePosition,
          [position],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void advanceWaypoint() => super.noSuchMethod(
        Invocation.method(
          #advanceWaypoint,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void revertWaypoint() => super.noSuchMethod(
        Invocation.method(
          #revertWaypoint,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deactivateRoute() => super.noSuchMethod(
        Invocation.method(
          #deactivateRoute,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearPosition() => super.noSuchMethod(
        Invocation.method(
          #clearPosition,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<void> saveRoute(_i7.Route? route) => (super.noSuchMethod(
        Invocation.method(
          #saveRoute,
          [route],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> deleteRoute(String? routeId) => (super.noSuchMethod(
        Invocation.method(
          #deleteRoute,
          [routeId],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<_i7.Route> createRoute({
    required String? name,
    required List<_i7.Waypoint>? waypoints,
    String? description,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRoute,
          [],
          {
            #name: name,
            #waypoints: waypoints,
            #description: description,
          },
        ),
        returnValue: _i13.Future<_i7.Route>.value(_FakeRoute_5(
          this,
          Invocation.method(
            #createRoute,
            [],
            {
              #name: name,
              #waypoints: waypoints,
              #description: description,
            },
          ),
        )),
      ) as _i13.Future<_i7.Route>);

  @override
  _i13.Future<void> loadSavedRoutes() => (super.noSuchMethod(
        Invocation.method(
          #loadSavedRoutes,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TimelineProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimelineProvider extends _i1.Mock implements _i22.TimelineProvider {
  MockTimelineProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get frameIndex => (super.noSuchMethod(
        Invocation.getter(#frameIndex),
        returnValue: 0,
      ) as int);

  @override
  int get frameCount => (super.noSuchMethod(
        Invocation.getter(#frameCount),
        returnValue: 0,
      ) as int);

  @override
  bool get hasFrames => (super.noSuchMethod(
        Invocation.getter(#hasFrames),
        returnValue: false,
      ) as bool);

  @override
  _i22.PlaybackState get playbackState => (super.noSuchMethod(
        Invocation.getter(#playbackState),
        returnValue: _i22.PlaybackState.paused,
      ) as _i22.PlaybackState);

  @override
  bool get isPlaying => (super.noSuchMethod(
        Invocation.getter(#isPlaying),
        returnValue: false,
      ) as bool);

  @override
  double get scrubberPosition => (super.noSuchMethod(
        Invocation.getter(#scrubberPosition),
        returnValue: 0.0,
      ) as double);

  @override
  String get activeTimeLabel => (super.noSuchMethod(
        Invocation.getter(#activeTimeLabel),
        returnValue: _i23.dummyValue<String>(
          this,
          Invocation.getter(#activeTimeLabel),
        ),
      ) as String);

  @override
  List<_i6.WindDataPoint> get activeWindPoints => (super.noSuchMethod(
        Invocation.getter(#activeWindPoints),
        returnValue: <_i6.WindDataPoint>[],
      ) as List<_i6.WindDataPoint>);

  @override
  List<_i6.WaveDataPoint> get activeWavePoints => (super.noSuchMethod(
        Invocation.getter(#activeWavePoints),
        returnValue: <_i6.WaveDataPoint>[],
      ) as List<_i6.WaveDataPoint>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void setFrameIndex(int? index) => super.noSuchMethod(
        Invocation.method(
          #setFrameIndex,
          [index],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setScrubberPosition(double? position) => super.noSuchMethod(
        Invocation.method(
          #setScrubberPosition,
          [position],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void nextFrame() => super.noSuchMethod(
        Invocation.method(
          #nextFrame,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void previousFrame() => super.noSuchMethod(
        Invocation.method(
          #previousFrame,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void play() => super.noSuchMethod(
        Invocation.method(
          #play,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pause() => super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void togglePlayback() => super.noSuchMethod(
        Invocation.method(
          #togglePlayback,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SettingsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsProvider extends _i1.Mock implements _i3.SettingsProvider {
  MockSettingsProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SpeedUnit get speedUnit => (super.noSuchMethod(
        Invocation.getter(#speedUnit),
        returnValue: _i3.SpeedUnit.knots,
      ) as _i3.SpeedUnit);

  @override
  _i3.DistanceUnit get distanceUnit => (super.noSuchMethod(
        Invocation.getter(#distanceUnit),
        returnValue: _i3.DistanceUnit.nauticalMiles,
      ) as _i3.DistanceUnit);

  @override
  _i3.DepthUnit get depthUnit => (super.noSuchMethod(
        Invocation.getter(#depthUnit),
        returnValue: _i3.DepthUnit.meters,
      ) as _i3.DepthUnit);

  @override
  bool get showCompass => (super.noSuchMethod(
        Invocation.getter(#showCompass),
        returnValue: false,
      ) as bool);

  @override
  bool get showDataOrbs => (super.noSuchMethod(
        Invocation.getter(#showDataOrbs),
        returnValue: false,
      ) as bool);

  @override
  bool get showSpeedArc => (super.noSuchMethod(
        Invocation.getter(#showSpeedArc),
        returnValue: false,
      ) as bool);

  @override
  bool get showWaveAnimation => (super.noSuchMethod(
        Invocation.getter(#showWaveAnimation),
        returnValue: false,
      ) as bool);

  @override
  String get language => (super.noSuchMethod(
        Invocation.getter(#language),
        returnValue: _i23.dummyValue<String>(
          this,
          Invocation.getter(#language),
        ),
      ) as String);

  @override
  int get mapRefreshRate => (super.noSuchMethod(
        Invocation.getter(#mapRefreshRate),
        returnValue: 0,
      ) as int);

  @override
  String get nmeaHost => (super.noSuchMethod(
        Invocation.getter(#nmeaHost),
        returnValue: _i23.dummyValue<String>(
          this,
          Invocation.getter(#nmeaHost),
        ),
      ) as String);

  @override
  int get nmeaPort => (super.noSuchMethod(
        Invocation.getter(#nmeaPort),
        returnValue: 0,
      ) as int);

  @override
  _i24.ConnectionType get nmeaConnectionType => (super.noSuchMethod(
        Invocation.getter(#nmeaConnectionType),
        returnValue: _i24.ConnectionType.tcp,
      ) as _i24.ConnectionType);

  @override
  bool get autoConnectNMEA => (super.noSuchMethod(
        Invocation.getter(#autoConnectNMEA),
        returnValue: false,
      ) as bool);

  @override
  String get mapTilerApiKey => (super.noSuchMethod(
        Invocation.getter(#mapTilerApiKey),
        returnValue: _i23.dummyValue<String>(
          this,
          Invocation.getter(#mapTilerApiKey),
        ),
      ) as String);

  @override
  bool get hasMapTilerApiKey => (super.noSuchMethod(
        Invocation.getter(#hasMapTilerApiKey),
        returnValue: false,
      ) as bool);

  @override
  String get aisStreamApiKey => (super.noSuchMethod(
        Invocation.getter(#aisStreamApiKey),
        returnValue: _i23.dummyValue<String>(
          this,
          Invocation.getter(#aisStreamApiKey),
        ),
      ) as String);

  @override
  bool get hasAisStreamApiKey => (super.noSuchMethod(
        Invocation.getter(#hasAisStreamApiKey),
        returnValue: false,
      ) as bool);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i13.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> setSpeedUnit(_i3.SpeedUnit? unit) => (super.noSuchMethod(
        Invocation.method(
          #setSpeedUnit,
          [unit],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> setDistanceUnit(_i3.DistanceUnit? unit) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDistanceUnit,
          [unit],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> setDepthUnit(_i3.DepthUnit? unit) => (super.noSuchMethod(
        Invocation.method(
          #setDepthUnit,
          [unit],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> setShowCompass(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setShowCompass,
          [value],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> setShowDataOrbs(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setShowDataOrbs,
          [value],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> setShowSpeedArc(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setShowSpeedArc,
          [value],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> setShowWaveAnimation(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setShowWaveAnimation,
          [value],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> setLanguage(String? lang) => (super.noSuchMethod(
        Invocation.method(
          #setLanguage,
          [lang],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> setMapRefreshRate(int? milliseconds) => (super.noSuchMethod(
        Invocation.method(
          #setMapRefreshRate,
          [milliseconds],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> setNMEAHost(String? host) => (super.noSuchMethod(
        Invocation.method(
          #setNMEAHost,
          [host],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> setNMEAPort(int? port) => (super.noSuchMethod(
        Invocation.method(
          #setNMEAPort,
          [port],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> setNMEAConnectionType(_i24.ConnectionType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNMEAConnectionType,
          [type],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> setAutoConnectNMEA(bool? autoConnect) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAutoConnectNMEA,
          [autoConnect],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> setMapTilerApiKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #setMapTilerApiKey,
          [key],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> setAisStreamApiKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #setAisStreamApiKey,
          [key],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> resetToDefaults() => (super.noSuchMethod(
        Invocation.method(
          #resetToDefaults,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ThemeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeProvider extends _i1.Mock implements _i25.ThemeProvider {
  MockThemeProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i25.AppThemeMode get themeMode => (super.noSuchMethod(
        Invocation.getter(#themeMode),
        returnValue: _i25.AppThemeMode.light,
      ) as _i25.AppThemeMode);

  @override
  _i26.ThemeVariant get themeVariant => (super.noSuchMethod(
        Invocation.getter(#themeVariant),
        returnValue: _i26.ThemeVariant.oceanGlass,
      ) as _i26.ThemeVariant);

  @override
  bool get isRedLightMode => (super.noSuchMethod(
        Invocation.getter(#isRedLightMode),
        returnValue: false,
      ) as bool);

  @override
  bool get isOceanGlass => (super.noSuchMethod(
        Invocation.getter(#isOceanGlass),
        returnValue: false,
      ) as bool);

  @override
  bool get isHolographic => (super.noSuchMethod(
        Invocation.getter(#isHolographic),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i8.ThemeData getTheme(_i15.Brightness? systemBrightness) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTheme,
          [systemBrightness],
        ),
        returnValue: _FakeThemeData_6(
          this,
          Invocation.method(
            #getTheme,
            [systemBrightness],
          ),
        ),
      ) as _i8.ThemeData);

  @override
  bool isDark(_i15.Brightness? systemBrightness) => (super.noSuchMethod(
        Invocation.method(
          #isDark,
          [systemBrightness],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i13.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> setThemeMode(_i25.AppThemeMode? mode) =>
      (super.noSuchMethod(
        Invocation.method(
          #setThemeMode,
          [mode],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> toggleTheme() => (super.noSuchMethod(
        Invocation.method(
          #toggleTheme,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> enableRedLightMode() => (super.noSuchMethod(
        Invocation.method(
          #enableRedLightMode,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> disableRedLightMode() => (super.noSuchMethod(
        Invocation.method(
          #disableRedLightMode,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> setThemeVariant(_i26.ThemeVariant? variant) =>
      (super.noSuchMethod(
        Invocation.method(
          #setThemeVariant,
          [variant],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> toggleThemeVariant() => (super.noSuchMethod(
        Invocation.method(
          #toggleThemeVariant,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
